TRUNCATE TABLE players RESTART IDENTITY CASCADE;
TRUNCATE TABLE teams RESTART IDENTITY CASCADE;


DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS teams;


SELECT * FROM players;
SELECT * FROM teams;